name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Run Test
        run: npm run test:cover
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
